name: clean_electric
version: 1.0.0+1
publish_to: none
description: A new Flutter project for UAP.
environment: 
  sdk: '>=2.17.5 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  uuid: ^3.0.5
  hive: ^2.0.5
  hive_flutter: ^1.1.0
  json_annotation: ^4.4.0
  path_provider: 2.0.11
  geolocator: ^9.0.2
  get_storage: 2.0.3
  expandable: ^5.0.1
  mobile_scanner: ^2.0.0
  clay_containers: ^0.3.2
  flutter_secure_storage: ^6.0.0
  google_fonts: ^3.0.1
  image_picker: ^0.8.5+3
  file_picker: ^4.5.1
  open_file: ^3.2.1
  flutter_downloader: ^1.8.0+1
  intl: ^0.17.0
  share_plus: ^4.0.9
  pinput: ^2.2.12
  datetime_picker_formfield: ^2.0.1
  flutter:
    sdk: flutter
  google_maps_flutter: ^2.2.1
  flutter_sticky_header: ^0.6.4
  flutter_osm_plugin: ^0.40.3

dev_dependencies:
  get_cli: any
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.9.3
  build_runner: ^2.1.7
  json_serializable: ^6.1.4
  hive_generator: ^1.1.2
  flutter_test:
    sdk: flutter

flutter: 
  uses-material-design: true

  assets:
    - assets/images/
    - assets/json/
    - assets/ca/

  #  flutter pub run flutter_launcher_icons:main

flutter_icons:
  android: "launcher_icon"
  image_path: "assets/images/library.png"


#  flutter pub run flutter_native_splash:create

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/images/splash.png
  android: true
  android_gravity: fill
  fullscreen: true
  ios: false
  web: false
#  android_12:
#    image: assets/images/splash.png
#    background_image_android: assets/images/splash.png
#    image_dark: assets/images/splash.png
#    fullscreen: true
#    android_gravity: fill
