// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRq_eXbbb2CvJr28BOJecxVSC7MlVZZUM',
    appId: '1:894275492909:web:b2af1e05f0dfad6df6aca4',
    messagingSenderId: '894275492909',
    projectId: 'cleanelectric',
    authDomain: 'cleanelectric.firebaseapp.com',
    storageBucket: 'cleanelectric.appspot.com',
    measurementId: 'G-3KW2TMRQPS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWRYzwVvlRatKVCmloQeQQyoZBvMaBBDA',
    appId: '1:894275492909:android:6a24b348276c1f44f6aca4',
    messagingSenderId: '894275492909',
    projectId: 'cleanelectric',
    storageBucket: 'cleanelectric.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAIUhru2yNHxkG8x4G-AOqsxHxSl4LRR-A',
    appId: '1:894275492909:ios:223ff637a81805dff6aca4',
    messagingSenderId: '894275492909',
    projectId: 'cleanelectric',
    storageBucket: 'cleanelectric.appspot.com',
    androidClientId: '894275492909-6ge0u4rsg44lbfbd30ok0ceq53tcfcr6.apps.googleusercontent.com',
    iosClientId: '894275492909-rq6p8fh14f5ecev6oqgchrc66fb0sbrc.apps.googleusercontent.com',
    iosBundleId: 'com.amitgunjan.cleanElectric',
  );
}
